// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCceAqgSuo6CpgxUGOz28fNdLrgByXqaA0',
    appId: '1:978489353241:web:e43d77506b09f4f7f2f688',
    messagingSenderId: '978489353241',
    projectId: 'aminacomedydemo',
    authDomain: 'aminacomedydemo.firebaseapp.com',
    storageBucket: 'aminacomedydemo.appspot.com',
    measurementId: 'G-0HLTVK2QWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9KhSMlu8OYur75GgpwbAmPKtbeabUh9A',
    appId: '1:978489353241:android:24c2abad53f01fd7f2f688',
    messagingSenderId: '978489353241',
    projectId: 'aminacomedydemo',
    storageBucket: 'aminacomedydemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjkUMV9Y77IooM_CKv-2tBQgswhd-iWpk',
    appId: '1:978489353241:ios:8f32395d8da176f1f2f688',
    messagingSenderId: '978489353241',
    projectId: 'aminacomedydemo',
    storageBucket: 'aminacomedydemo.appspot.com',
    iosClientId: '978489353241-kb1v1smdlnebh07j6vm89bcdv3h6l9m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjkUMV9Y77IooM_CKv-2tBQgswhd-iWpk',
    appId: '1:978489353241:ios:8f32395d8da176f1f2f688',
    messagingSenderId: '978489353241',
    projectId: 'aminacomedydemo',
    storageBucket: 'aminacomedydemo.appspot.com',
    iosClientId: '978489353241-kb1v1smdlnebh07j6vm89bcdv3h6l9m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
